version: 2

sphinx:
  configuration: docs/conf.py

build:
  image: latest

formats:
  - pdf
  - epub

python:
  version: 3.7
  install:
    - method: poetry
      path: .

commands:
  pre_build: poetry install